@echo off
echo Starting RevvHeadz Personal Garage App...
echo Starting Backend API on http://localhost:5050...
start cmd /k "cd /d "%~dp0server" && npm run dev"
echo Starting Frontend React App on http://localhost:5173...
start cmd /k "cd /d "%~dp0client" && npm run dev"
echo Done! Open http://localhost:5173 in your browser.
